version: '3.4'

services:

  sourcingdb:
   container_name: sourcingdb
   restart: always
   volumes:
    - ${WEBAPP_STORAGE_HOME}/site:/data/db
   ports:
    - "27017:27017" 

  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
        - sourcingdb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets